services:
  PurrmannWebsolutions\RouteNoteBundle\EventListener\NoteToolbarListener:
    class: PurrmannWebsolutions\RouteNoteBundle\EventListener\NoteToolbarListener
    autowire: true
    autoconfigure: true
    tags:
      - { name: kernel.event_subscriber }
