services:
  PurrmannWebsolutions\RouteNoteBundle\EventListener\NoteToolbarListener:
    class: PurrmannWebsolutions\RouteNoteBundle\EventListener\NoteToolbarListener
    arguments:
      - "@twig"
    tags:
      - { name: kernel.event_subscriber }
